### ISSUE TITLE
npm v7

### ISSUE THREAD

**Issue by deleonio** [leanupjs/leanup#35]
Issues:
- https://github.com/leanupjs/leanup/runs/1369188090?check_suite_focus=true#step:4:274

**Comment by bdsvc-github** [comment]
Deployment starting to ephemeral!

**Comment by bdsvc-github** [comment]
Deployed to ephemeral!

**Comment by martinoppitz** [comment]
https://github.com/Va1/string-replace-loader/pull/61/files

**Comment by martinoppitz** [comment]
https://github.com/Va1/string-replace-loader/compare/v2.3.0...v3.0.0

**Comment by martinoppitz** [comment]
move to release 1.2 because npm v7 not latest enough
