### ISSUE TITLE
Proof aurelia error with webpack v5 / or remove it

### ISSUE THREAD

**Issue by deleonio** [leanupjs/leanup#39]
https://github.com/aurelia/aurelia/issues/982

**Comment by martinoppitz** [comment]
https://github.com/aurelia/webpack-plugin/issues/166

**Comment by martinoppitz** [comment]
https://github.com/aurelia/webpack-plugin/search?q=BasicEvaluatedExpression

**Comment by martinoppitz** [comment]
https://github.com/aurelia/webpack-plugin/pull/169

**Comment by martinoppitz** [comment]
Sorry, we will remove Aurelia ... https://github.com/leanupjs/leanup/issues/55

**Comment by deleonio** [comment]
https://github.com/leanupjs/leanup/commit/8b3c20266bdb33832e4296d28e52639f69dc576b

**Comment by deleonio** [comment]
https://github.com/aurelia/webpack-plugin/pull/170

**Comment by deleonio** [comment]
@bigopon

We are back! Good job!

**Comment by deleonio** [comment]
Watch: https://github.com/aurelia/webpack-plugin/issues/187

**Comment by bigopon** [comment]
@deleonio thanks for the patient push. It wouldn't have happened without your effort. Appreciate it.

**Comment by deleonio** [comment]
it's done
