### ISSUE TITLE
Remove Babel from core, lint and test

### ISSUE THREAD

**Issue by martinoppitz** [leanupjs/leanup#45]
Use esbuild for core
Use ??? for lint
Use ts-node for test

**Comment by martinoppitz** [comment]
we cant remove babel - because Inferno provides only a babel transpiler - @Havunen

**Comment by Havunen** [comment]
Yes inferno officially has only babel transpiler
But I know @deamme has implemented plugin for typescript compiler here:
https://github.com/deamme/ts-transform-inferno

It would be good to have official typescript compiler

**Comment by martinoppitz** [comment]
Currently I only use Babel for JSX / TSX in the next version.
If I replace the Babel loader with the TS loader, then I'm about the same thing.

**Comment by martinoppitz** [comment]
I think it could be a topic for the next version (1.2.0).

We can replace Babel loader with TS loader. Many direct dependencies are removable.

Lint and test must be switched to ts-node, too.

**Comment by martinoppitz** [comment]
We could switch babel to ts-node in lint and mocha - https://github.com/leanupjs/leanup/issues/58

**Comment by martinoppitz** [comment]
**Babel** is needed by:
- angularjs
- inferno

**Comment by martinoppitz** [comment]
Create a new `@leanup` module named `cli-babel` as plugin.

**Comment by martinoppitz** [comment]
Babel removed:
- lint
- test
