### ISSUE TITLE
Consider using Neutrino for Webpack configuration

### ISSUE THREAD

**Issue by constgen** [leanupjs/leanup#51]
[Neutrino](https://neutrinojs.org/) is a tool for creating of shared webpack presets and middlwares. If you build your infrastructure with neutrino you have these benefits:
- Zero configuration by default
- Any Webpack setting is customizable by consumers
- Webpack configuration (Neutrino presets) still can be updated from NPM even after the installation
- A lot of community presets (SASS, LESS, Frameworks, Babel, Storybook, Eslint, Jest, etc.)
- You can compose presets and middlewares
- You can create your custom presets and build the next Create React App Killer

For example I have my personal list of middlewares as I share them between a lot of presets for React, Vue, Koa and others https://github.com/constgen/constgen-neutrino

**Comment by martinoppitz** [comment]
Hello @constgen,
Thank you for the information. I see we had a similar idea and our solutions are close together.

In detail there are some differences that we can consider.

Best regards

**Comment by constgen** [comment]
At least you can look at [webpack-chain](https://www.npmjs.com/package/webpack-chain) that is used under the hood of both Neutrino and Vue CLI
