### ISSUE TITLE
Mocha & babel config -> typescript files (with enums) in dependencies

### ISSUE THREAD

**Issue by BenICE** [leanupjs/leanup#58]
Situation:
- Leanup project with the standard config (e.g. tests are run via mocha)
- Project has a dependency to another project (like a rest-api generated via opengenerator, still in ts form) -> which creates an export for an enum
- If you use this enum in a test, the test cannot be executed anymore as we get a compile error

-> one solution is to let babel take all .ts / .tsx files

Currently the babel.register.js in cli-core-test checks only on `only: ['./node_modules/@leanup', './src', './tests']`
So it will not take the child project into account.

What would be the holdup to let it scan the whole path, like `only: ['./']` (which solves the problem with the enum as the babel loader knows how to handle it). It still only takes files with extension ts & tsx

**Comment by martinoppitz** [comment]
At the moment I could not reproduce the problem with the @ leanup/cli@1.0.47.

**Comment by BenICE** [comment]
@martinoppitz Do you have a branch somewhere with the discussed setup? I would have a look and try to break it

**Comment by martinoppitz** [comment]
To reproduce:

```bash
mkdir demo
cd demo
npm i @leanup/cli@1.0.47 @leanup/cli-react@1.0.47
npx lean create -o
npx lean test
```

**Comment by martinoppitz** [comment]
@BenICE remove the `tsconfig.json` from the openapi package.

![image](https://user-images.githubusercontent.com/6279703/100808158-e97a1280-3433-11eb-8814-a640e186e6bc.png)

**Comment by deleonio** [comment]
It is important, that no second tsconfig is inside the api module

**Comment by BenICE** [comment]
Unfortunatly after upgrading to 1.1, we are having the same issue again. 
Every Typescript specific syntax will create a problem (if it is in an imported file that comes from the node_modules folder).

No second tsconfig is present anymore. 
Currently no workaround known.

**Comment by deleonio** [comment]
Hint: @BenICE 

Take a look: https://leanupjs.org/1.2/guide/migration/#if-you-have-unsafe-eval-with-babel-runtime
